apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-demo
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    spec:
      containers:
        - image: nginxdemos/hello
          imagePullPolicy: IfNotPresent
          name: nginx-demo
          ports:
            - name: http
              protocol: TCP
              containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
              scheme: HTTP
            initialDelaySeconds: 30
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 30
          resources:
            requests:
              cpu: 100m
              memory: 100M
            limits:
              cpu: 1000m
              memory: 1024M
